meta_product_name: "WESOFOD"
meta_title: "The Welfare Society for the Disabled"
meta_description: "WESOFOD is a community-based NGO committed to improving the quality of lives of persons with disabilities in Kambia District, Sierra Leone."
meta_image: "wesofod.jpg"
